### ISSUE TITLE
TypeIt for VueJS

### ISSUE THREAD

**Issue by pirmax** [alexmacarthur/typeit#103]
Hello,

I am too new to this but could someone wear TypeIt in VueJS plugin?

Many thanks!

**Comment by alexmacarthur** [comment]
Stay tuned for this! Unless someone beats me to it, I'll at least put together a small CodePen example of a Vue component for TypeIt.

**Comment by pirmax** [comment]
I wrote this:

`<type-it :values="['Bird!', 'Snake!']" :speed="200" :loop="true"></type-it>`

```
  import Vue from 'vue'
  import TypeIt from 'typeit'

  Vue.component('type-it', {

    props: ['speed', 'values', 'loop', 'breakLines'],

    data() {
      return {
        speed: this.speed,
        values: this.values,
        loop: this.loop,
        breakLines: this.breakLines
      }
    },

    template: `<span class="type-it"></span>`,

    mounted () {
      new TypeIt(this.$el, {
        strings: this.values,
        breakLines: this.breakLines,
        loop: this.loop,
        speed: this.speed
      })
    }
  })
```

**Comment by alexmacarthur** [comment]
@pirmax Nice, thanks for sharing!

**Comment by timothymarois** [comment]
I too would like a better integration. Thanks @pirmax for the component. But what would allowing it to work with existing elements. I want to control it primarily through JS and not implement it via a html element since the html element already exist and has placeholder text. Would be great if this could replace the placeholder text with this on command. I'll mess around with it some more. 

Also to note, you should probably create a destroy method for the TypeIt instance if that component is removed.
