### ISSUE TITLE
Problems using TypeIt in React from npm install

### ISSUE THREAD

**Issue by dannymcgee** [alexmacarthur/typeit#111]
I've installed TypeIt with NPM to my React project, and I've imported it like this:

`import TypeIt from 'typeit';`

I'm trying to use it like this:

```
new TypeIt(typeItTarget, {
    strings: typeItContent.content,
    speed: 45,
    breakLines: false,
});
```

`typeItTarget` is a string formatted like this: "#line_&lt;number&gt;". I've verified that the string is correct and that the element it should point to actually exists in the DOM at the time the TypeIt instance is created. `TypeItContent.content` is an array of strings, which I have verified with a console log, but I've also tried hard-coding in an array of strings as well as a single string to test.

At first, the target element already had a div inside it containing the line number, and I noticed that the `.ti-container` element was wrapping that div as well. The cursor would appear on the correct line and blink, but no text was actually typed. At first I thought that the inner div might have been the problem, so I removed the id from the original target element and instead added it to a new, empty span alongside the line number div.

Now, I'm actually getting an error message:
**TypeError: matches is null**
```
  296 | //-- Create node of that string name.
  297 | var matches = string[0].match(/\<(.*?)\>/);
  298 | var _doc = document.implementation.createHTMLDocument("");
> 299 | _doc.body.innerHTML = "<" + matches[1] + "></" + matches[1] + ">";
  300 | 
  301 | //-- Add to the queue.
  302 | this.queue.push([this.type, _doc.body.children[0]]);
```

The element that I'm targeting, for the sake of clarity, looks like this:

```
<div class="ide-line">
    <div class="line-number">1</div>
    <span id="line_1" class="typeit-span"></span>
</div>
```
At first the line_1 id was on the `.ide-line`, but I moved it to the span when that wasn't working. I am seeing the new `.ti-container` span being added into the line_1 span.

Am I doing something wrong, or is this potentially a bug?

**Comment by alexmacarthur** [comment]
Thanks for reporting! Two things I'd check into here: 

1. I'm not that proficient in React, but I've read that if you're needing to reference specific DOM nodes, you should use `refs` instead of any other type of reference (like a '#id' string). Instead of passing `typeItTarget` as your target element, I'd make a ref and then pass that. You can see an example of that in this CodePen: https://codepen.io/alexmacarthur/pen/gXNyBJ. Also, the docs on refs might help: https://reactjs.org/docs/refs-and-the-dom.html

2. That `null` error you're getting is because it can't match find any HTML tags in the string it's trying to process. Do you have examples of the strings you're typing? There might be some odd character it didn't expect, or something else.

**Comment by dannymcgee** [comment]
Holy crap, using the ref instead of the ID totally worked. Thank you so much, I've been banging my head against this for hours. It's bizarre because I set up a totally fresh React app with nothing but a simple TypeIt call, using an ID there as well, and it worked just fine. I guess it's just inconsistent.

**Comment by alexmacarthur** [comment]
Great -- glad that worked!
