### ISSUE TITLE
Emojis have a extra character and then disappear.

### ISSUE THREAD

**Issue by CrazyVideoGamez** [alexmacarthur/typeit#208]
Why, when it is typing an emoji, it has a extra character?
![image](https://user-images.githubusercontent.com/59106025/80552386-78054d80-8994-11ea-9f4d-e9b8ad3e43bc.png)
When it is "Built by <em>people like you</em> ! 🤘🏻" without the extra character?

**Comment by alexmacarthur** [comment]
I'll check into this. Thanks for reporting!

**Comment by alexmacarthur** [comment]
So... kinda struggling with this one. I copied the exact version of the emoji you're having trouble with and was able to replicate the problem, and then realized that a _different_ version of the same emoji doesn't have any problem at all. For some reason, your version's unicode makeup doesn't bode well for being parsed the way TypeIt does so, and so it's having these weird issues. This emse sense since they even appear to have different "lengths" under the hood: 

![image](https://user-images.githubusercontent.com/8398220/80853594-a2a31080-8bf7-11ea-8457-2398646cfa2e.png)

I've spent a couple hours attempting to find a suitable workaround, but will have to table this for another time for now. As a temporary fix, I'd recommend using a different version of that emoji, like this one: 🤘
