### ISSUE TITLE
Break delay

### ISSUE THREAD

**Issue by devkick** [alexmacarthur/typeit#21]
.. insn't working for me. Any idea to solve this?

**Comment by alexmacarthur** [comment]
Hi, @devkick, if you send me your particular setup, I might be able to help troubleshoot. I'm not able to replicate this problem at all.

**Comment by ahmadassaf** [comment]
Hello @alexmacarthur an example .. go to http://ahmadassaf.com .. you can notice that the text immediately deletes with option `breakLine:false` and there is no delay at all.

You can easily replicate that even on http://macarthur.me/typeit/. Type multiple lines, break false and see what happens

**Comment by alexmacarthur** [comment]
Ah, I see what you mean -- this is because the `breakDelay` option only works if `breakLines` is set to `true`. With the current version, the only way to achieve that type of delay is by using the companion functions (tiType, tiPause, etc.) See this issue for more info: 

https://github.com/alexmacarthur/typeit/issues/16

Since this confusion has come up in the past, the next version will have a `deleteDelay` option, which will be effective when `breakLines` is set to `false`. I'm planning on releasing that in a couple of days.

**Comment by alexmacarthur** [comment]
P.S. - beautiful site!

**Comment by alexmacarthur** [comment]
Hi, @ahmadassaf -- letting you know there's a new release out that resolves this confusion by adding a `deleteDelay` option.

Thanks for using TypeIt! If you don't mind staring and/or sharing the project, I'd really appreciate it!

**Comment by ahmadassaf** [comment]
Hello @alexmacarthur thanks a lot for the prompt support and for your compliment .. am glad you liked the site
