### ISSUE TITLE
Cursor size does not get updated on screen resize

### ISSUE THREAD

**Issue by regularlabs** [alexmacarthur/typeit#227]
When resizing the window/screen (for instance also when changing orientation on a tablet/phone), the cursor does not update its size to match the changing responsive fontsize.

**Comment by regularlabs** [comment]
I have added this js code to my page to solve the issue:
```
	window.addEventListener('resize', () => {
		const cursor = document.querySelector('.ti-cursor');

		if (!cursor) {
			return;
		}

		cursor.style.font = window.getComputedStyle(cursor.parentElement).font;
	});
```

**Comment by alexmacarthur** [comment]
Yes... this is an interesting one. The reason I have the font set this way is due to the DOM work I have to do for cursor movement. For most people, it's likely not an issue, since people largely maintain their viewport size after loading the page. Could you describe your particular use case, so I can get a better idea of the best way to tackle this (if at all)? 

Sorry for the delay, by the way!

**Comment by regularlabs** [comment]
You can see it in action here:
https://regularlabs.com/articlesanywhere

**Comment by alexmacarthur** [comment]
@regularlabs Heads up, I just merged a change tonight that should make all of this easier. Not sure when it'll go out in the next release (bundling a few changes together for a probable major version bump soon), but it'll be in there whenever that time comes. 

In order to make all of this easier to work with, the change introduces custom properties for each of the font-related properties needed to be set: 

```
var(--ti-font-family, "default value");
var(--ti-font-weight, "default value");
var(--ti-font-size, "default value");
var(--ti-font-style, "default value");
var(--ti-line-height, "default value");
var(--ti-color', "default value");
```

That way, you can more easily control these styles via media queries however you'd like. For example: 

```css
      body {
        --ti-font-size: 30px;
      }

      @media screen and (min-width: 800px) {
        body {
          --ti-font-size: 60px;
        }
      }
```

... meaning no more weird JS event listening!

**Comment by regularlabs** [comment]
Ok, thanks.
