### ISSUE TITLE
callback fires on start not end

### ISSUE THREAD

**Issue by plagasul** [alexmacarthur/typeit#23]
It seems as if the callback is firing not when the typing ends but right when it starts, I am using it as such:

```
var theStrings = [  [ 'string one', 'string two' ]  ]

function cb(){
  console.log("callback");
}

$('#target').typeIt({
      strings:theStrings[0],
      cursor:false,
      speed:8,
      breakDelay:50,
      callback: cb()
 });
```

I also tried the callback "inline" as:

`callback: console.log("callback!")`

to no avail

Strange?

**Comment by alexmacarthur** [comment]
Hi, @plagasul --

This is happening because you're calling your callback using parentheses, which makes it immediately execute once the JavaScript is read on the page. If you change this: 

`callback: cb()`

to this: 

`callback: cb`

it will work as expected. Thanks for the question and I hope that helps!

Alex

**Comment by plagasul** [comment]
Ouch, but of course....  sorry about that. Thanks.
