### ISSUE TITLE
SEO effects?

### ISSUE THREAD

**Issue by jayelkaake** [alexmacarthur/typeit#268]
Really want to use this but I'm concerned it will have an affect on our SEO. Google uses the main heading as a way to describe the site and does process JS. 

Anyone know if this library addresses that concern, or if it's not a problem for sure?

**Comment by alexmacarthur** [comment]
Hi, @jayelkaake - sorry for the delay on this. I don't have any hard data on how an animation like this impacts SEO, but I built it early on to be able to work with hard-coded strings, so that JS-less web crawlers can crawl native HTML. You can read about that here: 

https://typeitjs.com/docs/vanilla/usage#hard-coded-in-html

The gist of it is setting your animation's API directly in your page's HTML. TypeIt will then automatically pick that up and use it as the string to type after it's initialized. The risk here is a potential flash of text before TypeIt has a chance to pick it up, so there is a trade-off.
