### ISSUE TITLE
[bug] Can't remove blinking cursor in option instance method

### ISSUE THREAD

**Issue by onlychans1** [alexmacarthur/typeit#284]

**Comment by eden-chan** [comment]
<img width="519" alt="image" src="https://user-images.githubusercontent.com/60107091/153956357-eba1808e-4d86-4637-afcf-1a70674c184a.png">

Setting cursor:false or waitUntilVisible: true does not seem to remove the blinking cursor if it's called in the getBeforeInit

**Comment by alexmacarthur** [comment]
Thanks for letting me know! I'll check it out.

**Comment by alexmacarthur** [comment]
Hi, @onlychans1 -- Sorry for the huge delay in getting back to you on this. At second glance, this issue is happening because you're not setting the `cursor` option in the `options` prop. The `.options()` instance method only works for certain settings ([read more here](https://www.typeitjs.com/docs/vanilla/instance-methods#options)).

Something like this would work for you:  

```jsx
<TypeIt 
    options={{ cursor: false }}
    getBeforeInit={(instance) => {
        instance.type("I am typing stuff");

        return instance;
    }}
/>
```
