### ISSUE TITLE
Doesnt work with input elements

### ISSUE THREAD

**Issue by Mohendran** [alexmacarthur/typeit#35]
typeit doesnt work with input elements...

**Comment by AkimaLunar** [comment]
I am curious about this too. Are there examples out there that use this plugin for an interactive, "fill the blanks", form? Sort of like `"My name is ________. I want to become an ___________"`?

**Comment by alexmacarthur** [comment]
Performing effects like this within inputs are quite different from non-inputs, and because of that and the relative low demand for the feature, I'm opting to pass on this for now (although, I'm always open to seeing a PR). 

@AkimaLunar If you want to simulate an effect like that, you could just use a `border-bottom` rule on an element to achieve the same result. See here: https://codepen.io/alexmacarthur/pen/pdXLRG
