### ISSUE TITLE
Ability turn off blinking cursor on completion or on .tiSettings() call

### ISSUE THREAD

**Issue by eamodio** [alexmacarthur/typeit#52]
First off -- excellent plugin!

It would be great if there was a way to turn off the blinking cursor either upon completion (maybe after a slight delay) or programmatically via `.tiSettings()`.

The blinking cursor is quite expensive (uses a lot of cpu) and while it looks great during the text animation, it is largely just wasting resources at the end.

Another option would be to allow an api or something to actually destroy the tracking on the element (but leaving the contents as is). That way once things are complete, there are no resources dedicated to them.

Thanks!

**Comment by alexmacarthur** [comment]
Hi, @eamodio --

A release just went out that should solve this. When you want to destroy an instance of TypeIt, call `.destroy()` on it. This will nullify the instance on all respective elements, as well as remove the cursor. 

Side note: The cursor blink is now controlled by CSS instead of the JS itself, which should help performance overall. 

Also, please note that following v5.0.0, the API for TypeIt is entirely different due to jQuery no longer being a dependency. 

```js
var instance = new TypeIt('#element, {
   strings: 'This is my string.'
});

//-- If you pass 'false,' the cursor will NOT be destroyed with the rest of the instance.
instance.destroy();
```
