### ISSUE TITLE
How to disable the typewriter on mobile phone ?

### ISSUE THREAD

**Issue by TheNexusDesigns** [alexmacarthur/typeit#79]
Hey, First of your script is phenomenal. I just want to disable the typewriter on mobile phones so it directly shows the text without a typing reveal on mobile phones.

I wrote the typeit typewriter text as strings like this:

> strings: ["text123", text456"],

in a .js file but all I want to do is to simply disable the typewriter on mobile view and have the text directly printed on the site with no typewriter effect on mobile view if possible. 

Thanks in advance and I'm looking forward to your reply.

**Comment by alexmacarthur** [comment]
Hi, @TheNexusDesigns -- glad you like the script! 

There's no built-in method to jump to the result (although I'm interested in this idea), but here are a couple of options: 

1. Define the strings in your element instead of the TypeIt instance. When the page loads, check viewport size, and conditionally initialize TypeIt.  

```
<script>
if(window.innerWidth > 640) {
   new TypeIt('#element');
}
</script>
<span id="element"><span id="element">text123<br>text456</span></span>
```

This way, the text will remain in the element on page load because it's actually part of the markup. 

2. Use JavaScript to detect viewport width, and on mobile, use it to manually add those strings to the element. 

Neither of those are the best solutions for this, but should get you by!

**Comment by TheNexusDesigns** [comment]
Thank you very much, will do this :smiley:  Hope there will be an option in the future to disable it on mobile phone like in wow.js where you just have to type "mobile:  false"  in the js options. 

But this will work too :) thanks again
